language: node_js
node_js:
  - "9"
dist: trusty
sudo: true
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://github.com/piotrek281097/bankAPI-front
